apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-messaging
    version: blue   # Change to 'green' when switching traffic
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
